### ISSUE TITLE
[Onion Messenger 구현] 구현 완료 CheckList

### ISSUE THREAD

**Issue by Hexife** [KAIST-IS521/2018s-onion-team2#14]
구현 완료된 파일들 체크해 주시면 감사드리겠습니당

### Client
- [ ] client/config
- [ ] client/gpg.cc
- [ ] client/gpg.hh
- [x] client/heartbeat.cc
- [x] client/heartbeat.hh
- [ ] client/main.cc
- [ ] client/message.cc
- [ ] client/message.hh
- [ ] client/nodelist.cc
- [ ] client/nodelist.hh
- [ ] client/parser.cc
- [x] client/parser.hh
- [ ] client/storage.cc
- [ ] client/storage.hh
- [ ] client/transmission.cc
- [x] client/transmission.hh
- [ ] client/ui.cc
- [ ] client/ui.hh
- [x] client/timestamp.cc
- [x] client/timestamp.hh

### Server
- [ ] server/hbchecker.cc
- [ ] server/hbchecker.hh
- [ ] server/main.cc
- [ ] server/nodelist.cc
- [ ] server/nodelist.hh

**Comment by sangkilc** [comment]
Is this up-to-date?

**Comment by leeswimming** [comment]
네 최신입니다. 하지만 현재 파일 하나씩 작성하는 것이 아니라 각 브랜치에서 여러 파일들을 병렬적으로 작성 중이어서 체크가 안된 파일들의 진행상황이 0%인 것은 아닙니다. 기능별로 이슈를 열고 기능별로 브랜치를 할당하는 방향으로 브랜치 사용방향을 수정하여 기능별 진행상황을 볼 수 있도록 수정할 계획입니다.

**Comment by leeswimming** [comment]
현재 이슈를 세부 이슈들로 분할했으므로 해당 이슈는 종료하도록 하겠습니다.
